scrape_configs:
- job_name: promitor
  scrape_interval: 5s
  metrics_path: /scrape
  static_configs:
    - targets: ['promitor.agents.scraper:88']
    - targets: ['otel-collector:8889']
    - targets: ['otel-collector:8888']