version: v1
azureMetadata:
  tenantId: e0372f7f-a362-47fb-9631-74a5c4ba8bbf
  subscriptionId: 63c590b6-4947-4898-92a3-cae91a31b5e4
  resourceGroupName: promitor-testing-infrastructure-europe
metricDefaults:
  aggregation:
    interval: 00:05:00
  limit: 10
  labels:
    geo: china
    environment: dev
  scraping:
    # Every minute
    schedule: "0 * * ? * *"
metrics:
  - name: whatever
    description: "Amount of orders created through custom metrics measured in Azure Application Insights"
    resourceType: ApplicationInsights
    azureMetricConfiguration:
      metric:
        name: Orders Created
        namespace: azure.applicationinsights
      dimension:
        #name: customDimensions/Tenant
        name: Tenant
      aggregation:
        type: Average
    resources:
      # Application Insights with data in the service itself (classic, deprecated)
    - name: promitor-automation-data-generation-we-telemetry-classic
      resourceGroupName: promitor-automation-data-generation
  #- name: promitor_demo_application_insights_orders_created
  #  description: "Amount of orders created through custom metrics measured in Azure Application Insights"
  #  resourceType: ApplicationInsights
  #  azureMetricConfiguration:
  #    metric:
  #      name: Orders Created
  #      namespace: azure.applicationinsights
  #    #dimension:
  #    #  name: Tenant
  #    aggregation:
  #      type: Average
  #  resources:
  #    # Application Insights with data in the service itself (classic, deprecated)
  #  - name: promitor-automation-data-generation-we-telemetry-classic
  #    resourceGroupName: promitor-automation-data-generation
  #    # Application Insights with data in Log Analytics
  #  - name: promitor-automation-data-generation-we-telemetry
  #    resourceGroupName: promitor-automation-data-generation
