version: v1
azureMetadata:
  tenantId: e0372f7f-a362-47fb-9631-74a5c4ba8bbf
  subscriptionId: 63c590b6-4947-4898-92a3-cae91a31b5e4
  resourceGroupName: promitor-automation-data-generation
metricDefaults:
  aggregation:
    interval: 00:05:00
  limit: 10
  labels:
    geo: china
    environment: dev
  scraping:
    # Every minute
    schedule: "0 * * ? * *"
metrics:
  - name: promitor_demo_application_insights_discovered
    description: "Average amount of exceptions measured in Azure Application Insights"
    resourceType: ApplicationInsights
    azureMetricConfiguration:
      metricName: exceptions/server
      aggregation:
        type: Average
    resources:
      # Application Insights with data in the service itself (classic, deprcated)
    - name: promitor-automation-data-generation-we-telemetry-classic