version: v1
azureMetadata:
  tenantId: c8819874-9e56-4e3f-b1a8-1c0325138f27
  subscriptionId: 0f9d7fea-99e8-4768-8672-06a28514f77e
  resourceGroupName: promitor
metricDefaults:
  aggregation:
    interval: 00:05:00
  limit: 10
  labels:
    geo: china
    environment: dev
  scraping:
    # Every minute
    schedule: "0 * * ? * *"
    # schedule: "* * * * *"
metrics:
- name: azure_cosmos_db_total_docs
  description: "Demo cosmos query"
  resourceType: CosmosDb
  azureMetricConfiguration:
    metricName: DocumentCount
    aggregation:
      type: Total
  resources:
  - dbName: promitor-cosmos-db
    resourceGroupName: promitor-sources